// <auto-generated />
namespace DawProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Role_TableV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_TableV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202101111438440_Role_TableV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
