// <auto-generated />
namespace DawProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class New_Column_AssignedID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Column_AssignedID));
        
        string IMigrationMetadata.Id
        {
            get { return "202101091655381_New_Column_AssignedID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
